name: Team awesome's approval workflow
on: pull_request_review

jobs:
  labelsWhenApproved:
    runs-on: ubuntu-latest
    steps:
      - name: STEP-17
        uses: pullreminders/label-when-approved-action@master
        env:
          APPROVALS: 1
          GITHUB_TOKEN: ${{secret.GITHUB_TOKEN}}
          ADD_LABEL: PASSED
